function Hd = fir_1
%FIR_1 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.8 and Signal Processing Toolbox 8.4.
% Generated on: 18-Nov-2020 15:51:00

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 5000;  % Sampling Frequency

N     = 1;        % Order
Fc    = 1500;     % Cutoff Frequency
flag  = 'scale';  % Sampling Flag
Alpha = 2.5;      % Window Parameter

% Create the window vector for the design algorithm.
win = gausswin(N+1, Alpha);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
